<a href="https://colab.research.google.com/github/pitapatat/wanted_pre_onboarding/blob/main/Hani_Bae_Week3_1_assignment_0313.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week3_1 Assignment

## [BASIC](#Basic) 
- 토크나이징이 완료된 위키 백과 코퍼스를 다운받고 **단어 사전을 구축하는 함수를 구현**할 수 있다.
- `Skip-Gram` 방식의 학습 데이터 셋을 생성하는 **Dataset과 Dataloader 클래스를 구현**할 수 있다.
- **Negative Sampling** 함수를 구현할 수 있다. 


## [CHALLENGE](#Challenge)
- Skip-Gram을 학습 과정 튜토리얼을 따라하며, **Skip-Gram을 학습하는 클래스를 구현**할 수 있다. 


## [ADVANCED](#Advanced)
- Skip-Gram 방식으로 word embedding을 학습하는 **Word2Vec 클래스를 구현**하고 실제로 학습할 수 있다.
- 학습이 완료된 word embedding을 불러와 **Gensim 패키지를 사용해 유사한 단어**를 뽑을 수 있다. 

### Reference
- [Skip-Gram negative sampling 한국어 튜토리얼](https://wikidocs.net/69141)
    - (참고) 위 튜토리얼에서는 target word와 context word 페어의 레이블은 1로, target word와 negative sample word 페어의 레이블은 0이 되도록 학습 데이터를 구현해 binary classification을 구현한다. 하지만 우리는 word2vec 논문 방식을 그대로 따르기 위해 label을 생성하지 않고 대신 loss 함수를 변행해서 binary classification을 학습할 것이다. 

In [ ]:
import os 
import sys
import pandas as pd
import numpy as np
import re
from typing import List, Dict
import random

In [ ]:
!pip install transformers

     |████████████████████████████████| 3.8 MB 6.9 MB/s 
     |████████████████████████████████| 67 kB 6.8 MB/s 
     |████████████████████████████████| 596 kB 71.4 MB/s 
     |████████████████████████████████| 895 kB 66.8 MB/s 
     |████████████████████████████████| 6.5 MB 54.3 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [ ]:
import torch
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F
from torch.optim import SGD
from transformers import get_linear_schedule_with_warmup
from torch.utils.data import Dataset, DataLoader
from tqdm import tqdm

In [ ]:
# seed
seed = 7777
np.random.seed(seed)
random.seed(seed)
torch.manual_seed(seed)
torch.cuda.manual_seed_all(seed)

In [ ]:
# device type
if torch.cuda.is_available():
    device = torch.device("cuda")
    print(f"# available GPUs : {torch.cuda.device_count()}")
    print(f"GPU name : {torch.cuda.get_device_name()}")
else:
    device = torch.device("cpu")
print(device)

# available GPUs : 1
GPU name : Tesla P100-PCIE-16GB
cuda


## Basic

### 토크나이징이 완료된 위키 백과 코퍼스 다운로드 및 불용어 사전 크롤링
- 나의 구글 드라이브에 데이터를 다운받아 영구적으로 사용할 수 있도록 하자. 
    - [데이터 다운로드 출처](https://ratsgo.github.io/embedding/downloaddata.html)
- 다운받은 데이터는 토크나이징이 완료된 상태이지만 불용어를 포함하고 있다. 따라서 향후 불용어를 제거하기 위해 불용어 사전을 크롤링하자. 
    - [불용어 사전 출처](https://www.ranks.nl/stopwords/korean)

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [ ]:
cd "/content/drive/MyDrive"

/content/drive/MyDrive


In [ ]:
!pip install gdown
### gdown accesse denied >> error 해결!!
#https://github.com/wkentaro/gdown/issues/43
!pip install --upgrade --no-cache-dir gdown

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  Created wheel for gdown: filename=gdown-4.4.0-py3-none-any.whl size=14774 sha256=45e0f4fe84602a78672af1e82afcd474210ba4672011e66c10b54fd4ef91e472
  Stored in directory: /tmp/pip-ephem-wheel-cache-9bo1zeu3/wheels/fb/c3/0e/c4d8ff8bfcb0461afff199471449f642179b74968c15b7a69c
Successfully built gdown
  Attempting uninstall: gdown
    Found existing installation: gdown 4.2.2
    Uninstalling gdown-4.2.2:
      Successfully uninstalled gdown-4.2.2


In [ ]:
# 데이터 다운로드
!gdown https://drive.google.com/u/0/uc?id=1Ybp_DmzNEpsBrUKZ1-NoPDzCMO39f-fx
!unzip tokenized.zip

Downloading...
From: https://drive.google.com/u/0/uc?id=1Ybp_DmzNEpsBrUKZ1-NoPDzCMO39f-fx
To: /content/drive/MyDrive/tokenized.zip
100% 873M/873M [00:04<00:00, 196MB/s]
Archive:  tokenized.zip
replace tokenized/korquad_mecab.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
  inflating: tokenized/korquad_mecab.txt  
  inflating: tokenized/wiki_ko_mecab.txt  
  inflating: tokenized/corpus_mecab_jamo.txt  
  inflating: tokenized/ratings_okt.txt  
  inflating: tokenized/ratings_khaiii.txt  
  inflating: tokenized/ratings_hannanum.txt  
  inflating: tokenized/ratings_soynlp.txt  
  inflating: tokenized/ratings_mecab.txt  
  inflating: tokenized/ratings_komoran.txt  


In [ ]:
# 한국어 불용어 리스트 크롤링
import requests
from bs4 import BeautifulSoup

url = "https://www.ranks.nl/stopwords/korean"
response = requests.get(url, verify = False)

if response.status_code == 200:
    soup = BeautifulSoup(response.text,'html.parser')
    content = soup.select_one('#article178ebefbfb1b165454ec9f168f545239 > div.panel-body > table > tbody > tr')
    stop_words=[]
    for x in content.strings:
        x=x.strip()
        if x:
            stop_words.append(x)
    print(f"# Korean stop words: {len(stop_words)}")
else:
    print(response.status_code)

/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)


# Korean stop words: 677


In [ ]:
stop_words[0]

'아'

### 단어 사전 구축 함수 구현 
- 문서 리스트를 입력 받아 사전을 생성하는 `make_vocab()` 함수를 구현하라.
- 함수 정의
    - 입력 매개변수
        - docs : 문서 리스트
        - min_count : 최소 단어 등장 빈도수 (단어 빈도가 `min_count` 미만인 단어는 사전에 포함하지 않음)
    - 조건
        - 문서 길이 제한
            - 단어 개수가 3개 이하인 문서는 처리하지 않음. (skip)
        - 사전에 포함되는 단어 빈도수 제한
            - 단어가 빈도가 `min_count` 미만은 단어는 사전에 포함하지 않음.
        - 불용어 제거 
            - 불용어 리스트에 포함된 단어는 제거 
    - 반환값 
        - word2count : 단어별 빈도 사전 (key: 단어, value: 등장 횟수)
        - wid2word : 단어별 인덱스(wid) 사전 (key: 단어 인덱스(int), value: 단어)
        - word2wid : 인덱스(wid)별 단어 사전 (key: 단어, value: 단어 인덱스(int))

In [ ]:
# 코퍼스 로드  
# pd.read_csv()로 한 경우, random.sample("df") << df는 sequece가 아니므로 작동 안됨 >> open > readlines()(파일내용 전체 리스트 반환)
#docs = pd.read_csv('/content/drive/MyDrive/tokenized/wiki_ko_mecab.txt', sep= '\t', header = None)

In [ ]:
with open('/content/drive/MyDrive/tokenized/wiki_ko_mecab.txt', 'r') as f:
    list_file = f.readlines()
docs = [line.rstrip('\n') for line in list_file]

In [ ]:
#docs[0]

In [ ]:
print(f"# wiki documents: {len(docs):,}")

# wiki documents: 311,237


In [ ]:
# 문서 개수를 500개로 줄임
docs=random.sample(docs, 500)

In [ ]:
print(f"# wiki documents: {len(docs):,}")

# wiki documents: 500


In [ ]:
#docs[499]

In [ ]:
''' 한글 코드 >> [^ ㄱ-ㅣ가-힣]+
## ㄱ ~ ㅎ: 0x3131 ~ 0x314e
ㅏ ~ ㅣ: 0x314f ~ 0x3163
가 ~ 힣: 0xac00 ~ 0xd7a3
'''

' 한글 코드 >> [^ ㄱ-ㅣ가-힣]+\n## ㄱ ~ ㅎ: 0x3131 ~ 0x314e\nㅏ ~ ㅣ: 0x314f ~ 0x3163\n가 ~ 힣: 0xac00 ~ 0xd7a3\n'

In [ ]:
#예시
#a =  docs[499]
#re.sub('[-=+,#/\?:^$.@*\"※~&%ㆍ!』\\‘|\(\)\[\]\<\>`\'…》A-Za-z0-9一-龥]',' ', a)

In [ ]:
# 문서 내 숫자, 영어 대소문자, 특수문자를 제거 (re package 사용)
for i in range(len(docs)):
    docs[i] = re.sub('[-=+,#/\?:^$.@*\"※~&%ㆍ!』/\\‘|\(\)\[\]\<\>《`\'…》A-Za-z0-9一-龥]',' ', docs[i])

In [ ]:
print(f"Check : {docs[0][:1000]}")

Check : 남모 공주            는 신라 의 공주   왕족 으로 법흥왕 과 보과 공주 부여 씨 의 딸 이 며 백제 동성왕 의 외손녀 였 다   경쟁자 인 준정 과 함께 신라 의 초대 여성 원화   화랑   였 다   그 가 준정 에게 암살 당한 것 을 계기 로 화랑 은 여성 이 아닌 남성 미소년 으로 선발 하 게 되 었 다   신라 진흥왕 에게 는 사촌 누나 이 자 이모 가 된다   신라 의 청소년 조직 이 었 던 화랑도 는 처음 에 는 남모   준정 두 미녀 를 뽑 아 이 를   원화 라 했으며 이 들 주위 에 는       여 명 의 무리 를 따르 게 하 였 다   그러나 준정 과 남모 는 서로 최고 가 되 고자 시기 하 였 다   준정 은 박영실 을 섬겼 는데   지소태후 는 자신 의 두 번 째 남편 이 기 도 한 그 를 싫어해서 준정 의 원화 를 없애 고 낭도 가 부족 한 남모 에게 위화랑 의 낭도 를 더 해 주 었 다   그 뒤 남모 는 준정 의 초대 로 그 의 집 에 갔 다가 억지로 권하 는 술 을 받아마시 고 취한 뒤 준정 에 의해 강물 에 던져져 살해 되 었 다   이 일 이 발각 돼 준 정도 사형 에 처해지 고 나라 에서 는 귀족 출신 의 잘 생기 고 품행 이 곧 은 남자 를 뽑 아 곱 게 단장 한 후 이 를 화랑 이 라 칭하 고 받들 게 하 였 다     부왕 신라 제     대 국왕 법흥왕 모후 보과 공주 부여 씨                   공주 남모 공주 외조부 백제 제     대 국왕 동성왕 외조모 신라 이찬 비지 의 딸   화랑전사 마루                  년   배우   박효빈   신라 법흥왕 백제 동성왕 준정 화랑 분류         년 죽음 분류   신라 의 왕녀 분류   신라 의 왕족 분류   화랑 분류   암살 된 사람 분류   독살 된 사람 분류   법흥왕


In [ ]:
from collections import Counter
def make_vocab(docs:List[str], min_count:int):
    """
    'docs'문서 리스트를 입력 받아 단어 사전을 생성.
    
    return 
        - word2count : 단어별 빈도 사전
        - wid2word : 단어별 인덱스(wid) 사전 
        - word2wid : 인덱스(wid)별 단어 사전
    """

    word2count = dict()
    word2id = dict()
    id2word = dict()

    #tqdm: 작업진행률 확인

        # 1. 문서 길이 제한 :단어 개수가 3개 이하인 문서는 처리하지 않음. (skip)
    doc_list = []
    for doc in tqdm(docs):
        if len(doc) >=3:
            doc_list.extend(doc.split())

        # 2. 임시 딕셔너리(_word2count)에 단어별 등장 빈도 기록 :단어가 빈도가 min_count 미만은 단어는 사전에 포함하지 않음
    doc_counts = Counter(doc_list)

    _word2count = dict()
    for key, val in doc_counts.items(): 
        if int(val) >= min_count:
            _word2count[key] = val 
  

    # 3. 불용어 제거: 불용어 리스트에 포함된 단어는 제거
    for key in list(_word2count.keys()):
        if key in stop_words:
            _word2count.pop(key)


        # 4. 토큰 최소 빈도를 만족하는 토큰만 사전에 추가
        word2count = _word2count
        for i, key in enumerate(word2count):
            word2id[key] = i
            id2word[i] = key 

    
    return word2count, word2id, id2word

In [ ]:
word2count, word2id, id2word = make_vocab(docs, min_count=5)

100%|██████████| 500/500 [00:00<00:00, 16591.00it/s]


In [ ]:
doc_len = sum(word2count.values()) # 문서 내 모든 단어의 개수 (단어별 등장 빈도의 총 합)
print(f"{doc_len:,}")

163,541


In [ ]:
print(f"# unique word : {len(word2id):,}")

# unique word : 5,880


In [ ]:
#id2word

In [ ]:
doc_list = [doc.split() for doc in docs]
#doc_list
# #사전에 존재하는 단어 리스트
word_lists = []
for doc in doc_list:
     word_in = []
     for word in doc:
         key = word2id.get(word, None)
         if key != None:
             word_in.append(key)
     word_lists.append(word_in)
print(word_lists[4])

[167, 20, 4, 5, 167, 8, 11, 96, 168, 169, 5, 35, 150, 23, 54, 92, 11, 168, 169, 5, 170, 168, 171, 169, 5, 172, 5, 173, 173, 174, 169, 175, 173, 174, 5, 176, 20, 176, 20, 177, 5, 20, 178, 179, 169, 20, 178, 179, 5, 180, 181, 181, 182, 168, 181, 182, 169, 180, 181, 181, 182, 5, 183, 181, 33, 184, 5, 185, 186, 176, 20, 169, 176, 20, 5, 187, 20, 99, 169, 187, 20, 99, 5, 169, 5, 181, 36, 169, 181, 36, 5, 188, 188, 175, 189, 190, 191, 143, 5, 191, 175, 191, 169, 191, 5, 192, 5, 169, 192, 191, 5, 5, 191, 5, 193, 5, 5, 5, 194, 175, 191, 5, 177, 5, 186, 195, 196, 169, 186, 195, 196, 5, 5, 197, 169, 197, 5, 169, 5, 198, 5, 199, 179, 20, 200, 5, 169, 187, 20, 201, 5, 5, 175, 202, 20, 203, 175, 204, 205, 5, 5, 206, 207, 198, 5, 206, 207, 208, 194, 175, 209, 180, 5, 210, 5, 211, 212, 5, 213, 17, 181, 214, 191, 5, 191, 5, 5, 17, 175, 5, 215, 191, 5, 216, 5, 176, 20, 5, 217, 175, 172, 5, 208, 194, 175, 5, 5, 218, 8, 5, 199, 205, 5, 5, 219, 220, 198, 5, 221, 214, 222, 198, 5, 223, 139, 133, 5, 224, 5,

In [ ]:
len(word_lists)

500

In [ ]:
# window_size = 2
# pair_list = []
# for words in word_lists[:2]:
#     list_pair= []
#     for i, idx in enumerate(words):
#         if i-window_size >= 0 and i+ window_size < len(words):
#             neighbor = words[i-window_size:i] + words[i+1:i+1+window_size]
#             target = words[i]
#             list_pair.append((target, neighbor))
#     pair_list.append(list_pair)
        
# print(pair_list)

In [ ]:
#pair_list[0]

In [ ]:
# pair = []
# for pair in pair_list:
#     tuple_list = []
#     for i in range(len(pair)):
#         target = pair[i][0]
#         for j in range(window_size*2):
#             neighbor = pair[i][1][j]
#             #val = tuple([target, neighbor])
#             tuple_list.append(tuple([target, neighbor]))
# print(tuple_list)

### Dataset 클래스 구현
- Skip-Gram 방식의 학습 데이터 셋(`Tuple(target_word, context_word)`)을 생성하는 `CustomDataset` 클래스를 구현하라.
- 클래스 정의
    - 생성자(`__init__()` 함수) 입력 매개변수
        - docs: 문서 리스트
        - word2id: 단어별 인덱스(wid) 사전
        - window_size: Skip-Gram의 윈도우 사이즈
    - 메소드
        - `make_pair()`
            - 문서를 단어로 쪼개고, 사전에 존재하는 단어들만 단어 인덱스로 변경
            - Skip-gram 방식의 `(target_word, context_word)` 페어(tuple)들을 `pairs` 리스트에 담아 반환
        - `__len__()`
            - `pairs` 리스트의 개수 반환
        - `__getitem__(index)`
            - `pairs` 리스트를 인덱싱
    - 주의 사항
        - `nn.Module`를 부모 클래스로 상속 받음 


In [ ]:
class CustomDataset(Dataset):
    """
    문서 리스트를 받아 skip-gram 방식의 (target_word, context_word) 데이터 셋을 생성
    """
    def __init__(self, docs:List[str], word2id:Dict[str,int], window_size:int=5):
        self.docs = docs
        self.word2id = word2id
        self.window_size = window_size
        self.pairs = self.make_pair()

    
    def make_pair(self):
        """
        (target, context) 형식의 Skip-gram pair 데이터 셋 생성 
        """
        #문서를 단어로 쪼갠 것
        doc_list = [doc.split() for doc in docs]
        #사전에 존재하는 단어 리스트
        word_lists = []
        for doc in doc_list:
            word_in = []
            for word in doc:
                key = word2id.get(word, None)
                if key != None:
                    word_in.append(key)
            word_lists.append(word_in)
        
        ###################################################################################오류 ##################수정 필요############
        #skipgram 방식의 pair_list =[target, (neighbor)]
        pair_list = []
        for words in word_lists:
            list_pair= []
            for i, idx in enumerate(words):
                if i-1-self.window_size >= 0 and i-1+ self.window_size < len(words):
                    neighbor = words[i-1-self.window_size:i-1] + words[i-1:i-1+self.window_size]
                    target = words[i-1]
                    list_pair.append((target, neighbor))
            pair_list.append(list_pair)               
        #print(pair_list)

        #pairs = (target, neighbor)
        pairs = []
        for pair in pair_list:
            pair_unit = []
            for i in range(len(pair)):
                target = pair[i][0]
                for j in range(self.window_size*2):
                    neighbor = pair[i][1][j]
                    pair_unit.append(tuple([target, neighbor]))
            pairs.extend(pair_unit)    ## 문제에서 요구하는건 dateset 통으로 >> append 아닌 extend
        #print(pairs)
        return pairs
        
    def __len__(self):
        return len(self.pairs)
    
    def __getitem__(self, idx):
        return self.pairs[idx]

In [ ]:
dataset = CustomDataset(docs, word2id, window_size=5)

In [ ]:
len(dataset)

2256850

In [ ]:
dataset[0]

(1, 0)

In [ ]:
# verify (target word, context word)
for i, pair in enumerate(dataset):
    if i==100:
        break
    print(f"({id2word[pair[0]]}, {id2word[pair[1]]})")
    

(공주, 남모)
(공주, 공주)
(공주, 는)
(공주, 신라)
(공주, 왕족)
(공주, 공주)
(공주, 왕족)
(공주, 부여)
(공주, 부여)
(공주, 공주)
(왕족, 공주)
(왕족, 는)
(왕족, 신라)
(왕족, 왕족)
(왕족, 공주)
(왕족, 왕족)
(왕족, 부여)
(왕족, 부여)
(왕족, 공주)
(왕족, 부여)
(부여, 는)
(부여, 신라)
(부여, 왕족)
(부여, 공주)
(부여, 왕족)
(부여, 부여)
(부여, 부여)
(부여, 공주)
(부여, 부여)
(부여, 씨)
(부여, 신라)
(부여, 왕족)
(부여, 공주)
(부여, 왕족)
(부여, 부여)
(부여, 부여)
(부여, 공주)
(부여, 부여)
(부여, 씨)
(부여, 왕족)
(공주, 왕족)
(공주, 공주)
(공주, 왕족)
(공주, 부여)
(공주, 부여)
(공주, 공주)
(공주, 부여)
(공주, 씨)
(공주, 왕족)
(공주, 딸)
(부여, 공주)
(부여, 왕족)
(부여, 부여)
(부여, 부여)
(부여, 공주)
(부여, 부여)
(부여, 씨)
(부여, 왕족)
(부여, 딸)
(부여, 며)
(씨, 왕족)
(씨, 부여)
(씨, 부여)
(씨, 공주)
(씨, 부여)
(씨, 씨)
(씨, 왕족)
(씨, 딸)
(씨, 며)
(씨, 며)
(왕족, 부여)
(왕족, 부여)
(왕족, 공주)
(왕족, 부여)
(왕족, 씨)
(왕족, 왕족)
(왕족, 딸)
(왕족, 며)
(왕족, 며)
(왕족, 백제)
(딸, 부여)
(딸, 공주)
(딸, 부여)
(딸, 씨)
(딸, 왕족)
(딸, 딸)
(딸, 며)
(딸, 며)
(딸, 백제)
(딸, 왕족)
(며, 공주)
(며, 부여)
(며, 씨)
(며, 왕족)
(며, 딸)
(며, 며)
(며, 며)
(며, 백제)
(며, 왕족)
(며, 였)


### 위에서 생성한 `dataset`으로 DataLoader  객체 생성
- `DataLoader` 클래스로 `train_dataloader`객체를 생성하라. 
    - 생성자 매개변수와 값
        - dataset = 위에서 생성한 dataset
        - batch_size = 64
        - shuffle = True

In [ ]:
dataset = CustomDataset(docs, word2id, window_size=5)

In [ ]:
train_dataloader = DataLoader(dataset, 
                              batch_size = 64,
                              shuffle = True

)

In [ ]:
len(train_dataloader)

35264

### Negative Sampling 함수 구현
- Skip-Gram은 복잡도를 줄이기 위한 방법으로 negative sampling을 사용한다. 
- `sample_table`이 다음과 같이 주어졌을 때, sample_table에서 랜덤으로 값을 뽑아 (batch_size, n_neg_sample) shape의 matrix를 반환하는 `get_neg_v_negative_sampling()`함수를 구현하라. 
- Sample Table은 negative distribution을 따른다. 
    - [negative distribution 설명](https://aegis4048.github.io/optimize_computational_efficiency_of_skip-gram_with_negative_sampling#How-are-negative-samples-drawn?)
- 함수 정의
    - 입력 매개변수
        - batch_size : 배치 사이즈, matrix의 row 개수 
        - n_neg_sample : negative sample의 개수, matrix의 column 개수
    - 반환값 
        - neg_v : 추출된 negative sample (2차원의 리스트)


In [ ]:
# negative sample을 추출할 sample table 생성 (해당 코드를 참고)
sample_table = []
sample_table_size = doc_len  #단어별 등장빈도 총합

# noise distribution 생성
alpha = 3/4
frequency_list = np.array(list(word2count.values())) ** alpha
Z = sum(frequency_list)
ratio = frequency_list/Z
negative_sample_dist = np.round(ratio*sample_table_size)

for wid, c in enumerate(negative_sample_dist):
    sample_table.extend([wid]*int(c))

In [ ]:
len(sample_table)

163355

In [ ]:
batch_size = 4
n_neg_sample = 5
q = np.random.choice(sample_table, (batch_size, n_neg_sample))
q

array([[2438,   20, 2201,  948, 1054],
       [ 344, 5697,   20,  797,  411],
       [ 831,  703, 1615, 2085, 2712],
       [3530, 2653, 2123,   23,  433]])

In [ ]:
def get_neg_v_negative_sampling(batch_size:int, n_neg_sample:int):
    """
    위에서 정의한 sample_table에서 (batch_size, n_neg_sample) shape만큼 랜덤 추출해 "네거티브 샘플 메트릭스"를 생성
    np.random.choice() 함수 활용 (위에서 정의한 sample_table을 함수의 argument로 사용)
    """
    neg_v = np.random.choice(sample_table, (batch_size, n_neg_sample))
    
    return neg_v

In [ ]:
get_neg_v_negative_sampling(4, 5)

array([[  95, 1522, 3943,   51, 5365],
       [  91, 2434,  490,    2,  587],
       [ 729,   83, 2090,  862,  451],
       [4581, 2827,   57, 1606, 1379]])

## Challenge

### 미니 튜토리얼
- 아래 튜토리얼을 따라하며 Skip-Gram 모델의 `forward` 및 `loss` 연산 방식을 이해하자
- Reference
    - [torch.nn.Embedding](https://pytorch.org/docs/stable/generated/torch.nn.Embedding.html)
    - [torch bmm](https://pytorch.org/docs/stable/generated/torch.bmm.html)
    - [Skip-Gram negative sampling loss function 설명 영문 블로그](https://aegis4048.github.io/optimize_computational_efficiency_of_skip-gram_with_negative_sampling#Derivation-of-Cost-Function-in-Negative-Sampling)
    - [Skip-Gram negative sampling loss function 설명 한글 블로그](https://reniew.github.io/22/)

In [ ]:
# hyper parameter example
emb_size = 30000 # vocab size
emb_dimension = 300 # word embedding 차원
n_neg_sample = 5
batch_size = 32

In [ ]:
# 1. Embedding Matrix와 Context Matrix를 생성
u_embedding = nn.Embedding(emb_size, emb_dimension, sparse=True).to(device)
v_embedding = nn.Embedding(emb_size, emb_dimension, sparse=True).to(device)

In [ ]:
# 2. wid(단어 인덱스)를 임의로 생성
pos_u = torch.randint(high = emb_size, size = (batch_size,))
pos_v = torch.randint(high = emb_size, size = (batch_size,))
neg_v = get_neg_v_negative_sampling(batch_size, n_neg_sample)
print(f"Target word idx : {pos_u} Pos context word idx : {pos_v} Neg context word idx : {neg_v}\n")

Target word idx : tensor([24912, 17289, 12910,  2559, 12326, 27555, 23130, 27934, 15182, 24236,
        24332,  8710, 24734, 18293,  5763,  7206, 21829, 21916,  7559, 25700,
        17538,  9671, 10080,  9851, 18343, 29882, 27734, 15472,  9884, 27090,
         7445, 29345]) Pos context word idx : tensor([ 2106, 24805,  3470, 27587,  1701,  1286, 24877, 14064, 15501,  3052,
        26884, 16798, 20775, 16434, 28191, 23326, 11902,  7991,  7144, 15670,
        23655,  5007,  5479,  1307, 28772, 18687, 21962, 12154, 20946, 25284,
        22784, 18920]) Neg context word idx : [[2300  675 5064    2 3359]
 [ 641   83  755   83 4366]
 [ 591   54  144  506  705]
 [2583 2384 1930   24 4585]
 [  92  199  576 1144 3743]
 [2842 3912 1106   92 4156]
 [   2  413  576 1371 2000]
 [5399  810 5300 3999   11]
 [1317 3918 2245 1416   54]
 [5365 2123  752 3022  156]
 [1100    2 4972 5226 2196]
 [4504 2531 3152 2751 2155]
 [2223   54 1808   60 1321]
 [ 127 4396 5500 5524   92]
 [4085 4013 5524 2957 3798]
 [

In [ ]:
# 3. tensor로 변환
pos_u = Variable(torch.LongTensor(pos_u)).to(device)
pos_v = Variable(torch.LongTensor(pos_v)).to(device)
neg_v = Variable(torch.LongTensor(neg_v)).to(device)

In [ ]:
# 4. wid로 각각의 embedding matrix에서 word embedding 값을 가져오기
pos_u = u_embedding(pos_u)
pos_v = v_embedding(pos_v)
neg_v = v_embedding(neg_v)
print(f"shape of pos_u embedding : {pos_u.shape}\n shape of pos_v embedding : {pos_v.shape}\n shape of neg_v embedding : {neg_v.shape}")


shape of pos_u embedding : torch.Size([32, 300])
 shape of pos_v embedding : torch.Size([32, 300])
 shape of neg_v embedding : torch.Size([32, 5, 300])


In [ ]:
# 5. dot product 
pos_score = torch.mul(pos_u, pos_v) # 행렬 element-wise 곱
pos_score = torch.sum(pos_score, dim=1)
print(f"shape of pos logits : {pos_score.shape}\n")

neg_score = torch.bmm(neg_v, pos_u.unsqueeze(dim=2)).squeeze()
print(f"shape of logits : {neg_score.shape}")

shape of pos logits : torch.Size([32])

shape of logits : torch.Size([32, 5])


In [ ]:
# 6. loss 구하기
pos_score = F.logsigmoid(pos_score)
neg_score = F.logsigmoid(-1*neg_score) # negative의 logit은 minimize 하기 위해 -1 곱함
print(f"pos logits : {pos_score.sum()}")
print(f"neg logits : {neg_score.sum()}")
loss = -1 * (torch.sum(pos_score) + torch.sum(neg_score))
print(f"Loss : {loss}")

pos logits : -216.42654418945312
neg logits : -1058.96533203125
Loss : 1275.391845703125


### Skip-gram 클래스 구현
- Skip-Gram 방식으로 단어 embedding을 학습하는 `SkipGram` 클래스를 구현하라.
- 클래스 정의
    - 생성자(`__init__()` 함수) 입력 매개변수
        - `vocab_size` : 사전내 단어 개수
        - `emb_dimension` : 엠베딩 크기
        - `device` : 연산 장치 종류
    - 생성자에서 생성해야할 변수 
        - `vocab_size` : 사전내 단어 개수
        - `emb_dimension` : 엠베딩 크기
        - `u_embedding` : (vocab_size, emb_dimension) 엠베딩 메트릭스 (target_word)
        - `v_embedding` : (vocab_size, emb_dimension) 엠베딩 메트릭스 (context_word)
    - 메소드
        - `init_embedding()` (제공됨)
            - 엠베딩 메트릭스 값을 초기화
        - `forward()`
            - 위 튜토리얼과 같이 dot product를 수행한 후 score를 생성
            - loss를 반환 (loss 설명 추가)
        - `save_emedding()` (제공됨)
            - `u_embedding`의 단어 엠베딩 값을 단어 별로 파일에 저장
    - 주의 사항     
        - `nn.Module`를 부모 클래스로 상속 받음 

In [ ]:
class SkipGram(nn.Module):
    def __init__(self, vocab_size:int, emb_dimension:int, device:str):
        super(SkipGram, self).__init__()
        self.vocab_size = vocab_size
        self.emb_dimension = emb_dimension
        self.u_embedding = nn.Embedding(vocab_size, emb_dimension, sparse=True).to(device)
        self.v_embedding = nn.Embedding(vocab_size, emb_dimension, sparse=True).to(device)
        self.init_embedding()
    
    
    def init_embedding(self):
        """
        u_embedding과 v_embedding 메트릭스 값을 초기화
        """
        initrange = 0.5 / self.emb_dimension
        self.u_embedding.weight.data.uniform_(-initrange, initrange)
        self.v_embedding.weight.data.uniform_(-0, 0)
    
    
    def forward(self, pos_u, pos_v, neg_v):
        """
        dot product를 수행한 후 score를 생성
        loss 반환
        """    


        # 각각의 embedding matrix에서 word embedding 값을 가져오기

        # pos_u = Variable(torch.LongTensor(pos_u)).to(device)
        # pos_v = Variable(torch.LongTensor(pos_v)).to(device)
        # neg_v = Variable(torch.LongTensor(neg_v)).to(device)

        pos_u = self.u_embedding(pos_u)
        pos_v = self.v_embedding(pos_v)
        neg_v = self.v_embedding(neg_v)

        # dot product 
        pos_score = torch.mul(pos_u, pos_v)
        pos_score = torch.sum(pos_score, dim=1)
        neg_score = torch.bmm(neg_v, pos_u.unsqueeze(dim=2)).squeeze()
        

        # loss 구하기
        pos_score = F.logsigmoid(pos_score)
        neg_score = F.logsigmoid(-1*neg_score)
        loss = -1 * (torch.sum(pos_score) + torch.sum(neg_score))

        return loss
    
    def save_embedding(self, id2word, file_name, use_cuda):
        """
        'file_name' 위치에 word와 word_embedding을 line-by로 저장
        파일의 첫 줄은 '단어 개수' 그리고 '단어 embedding 사이즈' 값을 입력해야 함
        """
        if use_cuda: # parameter를 gpu 메모리에서 cpu 메모리로 옮김
            embedding = self.u_embedding.weight.cpu().data.numpy()
        else:
            embedding = self.u_embedding.weight.data.numpy()

        with open(file_name, 'w') as writer:
            # 파일의 첫 줄은 '단어 개수' 그리고 '단어 embedding 사이즈' 값을 입력해야 함
            writer.write(f"{len(id2word)} {embedding.shape[-1]}\n")
            
            for wid, word in id2word.items():
                e = embedding[wid]
                e = " ".join([str(e_) for e_ in e])
                writer.write(f"{word} {e}\n")

## Advanced

### Skip-Gram 방식의  Word2Vec 클래스 구현
- Skip-Gram 방식으로 단어 embedding을 학습하는 `Word2Vec` 클래스를 구현하라.
- 클래스 정의
    - 생성자(`__init__()`) 입력 매개 변수
        - `input_file` : 학습할 문서 리스트
        - `output_file_name` : 학습된 word embedding을 저장할 파일 위치
        - `device` : 연상 장치 종류
        - `emb_dimension` : word embedding 차원
        - `batch_size` : 학습 배치 사이즈
        - `window_size` : skip-gram 윈도우 사이즈 (context word 개수를 결정)
        - `n_neg_sample` : negative sample 개수
        - `iteration` : 학습 반복 횟수
        - `lr` : learning rate
        - `min_count` : 사전에 추가될 단어의 최소 등장 빈도
    - 생성자에서 생성해야 할 변수 
        - `docs` : 학습할 문서 리스트
        - `output_file_name` : 학습된 word embedding을 저장할 파일 위치
        - `word2count`, `word2id`, `id2word` : 위에서 구현한 `make_vocab()` 함수의 반환 값
        - `device` : 연산 장치 종류
        - `emb_size` : vocab의 (unique한) 단어 종류 
        - `emb_dimension` : word embedding 차원
        - `batch_size` : 학습 배치 사이즈
        - `window_size` : skip-gram 윈도우 사이즈 (context word 개수를 결정)
        - `n_neg_sample` : negative sample 개수
        - `iteration` : 학습 반복 횟수
        - `lr` : learning rate
        - `model` : `SkipGram` 클래스의 인스턴스
        - `optimizer` : `SGD` 클래스의 인스턴스
    - 메소드
        - `train()`
            - 입력 매개변수 
                - `train_dataloader`
            - Iteration 횟수만큼 input_file 학습 데이터를 학습한다. 매 epoch마다 for loop 돌면서 batch 단위 학습 데이터를 skip gram 모델에 학습함. 학습이 끝나면 word embedding을 output_file_name 파일에 저장.
- Reference
    - [Optimizer - SGD](https://pytorch.org/docs/stable/generated/torch.optim.SGD.html)

In [ ]:
!pwd

/content/drive/MyDrive


In [ ]:
# device type
if torch.cuda.is_available():
    device = torch.device("cuda")
    print(f"# available GPUs : {torch.cuda.device_count()}")
    print(f"GPU name : {torch.cuda.get_device_name()}")
else:
    device = torch.device("cpu")
print(device)

# available GPUs : 1
GPU name : Tesla P100-PCIE-16GB
cuda


In [ ]:
class Word2Vec:
    def __init__(self, 
                input_file: List[str],
                output_file_name: str,
                 device: str,
                 emb_dimension=300,
                 batch_size = 64,
                 window_size=5,
                 n_neg_sample = 5,
                 iteration=1,
                 lr = 0.02,
                 min_count=5):
        self.docs = input_file
        self.output_file_name = output_file_name
        self.word2count, self.word2id, self.id2word = make_vocab(input_file, min_count)
        self.device = device
        self.emb_size = len(self.word2id)
        self.emb_dimension = emb_dimension
        self.batch_size = batch_size
        self.window_size = window_size
        self.n_neg_sample = n_neg_sample
        self.iteration = iteration
        self.lr = lr
        self.model = SkipGram(self.emb_size, emb_dimension, device)
        self.optimizer = torch.optim.SGD(self.model.parameters(), lr) # torch.optim.SGD 클래스 사용

        # train() 함수에서 만든 임베딩 결과 파일들을 저장할 폴더 생성 (os.makedirs 사용)
        ############## 이거때문에 너무 해맸다!! ############################
        if not os.path.exists(self.output_file_name):
            os.makedirs(self.output_file_name) 
        #self.model.save_embedding(self, self.id2word, os.makedirs('/content/drive/MyDrive/processed/',exist_ok=True), use_cuda)   
       
        
    
    def train(self, train_dataloader):
        
        # lr 값을 조절하는 스케줄러 인스턴스 변수를 생성
        self.scheduler = get_linear_schedule_with_warmup(
            optimizer = self.optimizer,
            num_warmup_steps=0,
            num_training_steps= len(train_dataloader)
        )
        
        for epoch in range(self.iteration):
            
            print(f"*****Epoch {epoch} Train Start*****")
            print(f"*****Epoch {epoch} Total Step {len(train_dataloader)}*****")
            total_loss, batch_loss, batch_step = 0,0,0

            for step, batch in enumerate(train_dataloader):
                batch_step+=1

                pos_u, pos_v = batch
                # negative data 생성
                neg_v = get_neg_v_negative_sampling(pos_u.shape[0], self.n_neg_sample)
                
                # 데이터를 tensor화 & device 설정
                pos_u = Variable(torch.LongTensor(pos_u)).to(device)
                pos_v = Variable(torch.LongTensor(pos_v)).to(device)
                neg_v = Variable(torch.LongTensor(neg_v)).to(device)

                # model의 gradient 초기화
                self.model.zero_grad()
                # optimizer의 gradient 초기화
                self.optimizer.zero_grad()

                # forward
                loss = self.model.forward(pos_u, pos_v, neg_v)

                # loss 계산
                loss.backward()

                # optimizer 업데이트
                self.optimizer.step() 
                # scheduler 업데이트
                self.scheduler.step()

                batch_loss += loss.item()
                total_loss += loss.item()
                
                if (step%500 == 0) and (step!=0):
                    print(f"Step: {step} Loss: {batch_loss/batch_step:.4f} lr: {self.optimizer.param_groups[0]['lr']:.4f}")
                    # 변수 초기화    
                    batch_loss, batch_step = 0,0
            
            print(f"Epoch {epoch} Total Mean Loss : {total_loss/(step+1):.4f}")
            print(f"*****Epoch {epoch} Train Finished*****\n")
            
            print(f"*****Epoch {epoch} Saving Embedding...*****")
            self.model.save_embedding(self.id2word, os.path.join(self.output_file_name, f'w2v_{epoch}.txt'), True if 'cuda' in self.device.type else False)
            print(f"*****Epoch {epoch} Embedding Saved at {os.path.join(self.output_file_name, f'w2v_{epoch}.txt')}*****\n")

In [ ]:
output_file = os.path.join(".", "word2vec_wiki")
# Word2Vec 클래스의 인스턴스 생성
w2v = Word2Vec(docs, output_file, device, n_neg_sample=10, iteration=3)

100%|██████████| 500/500 [00:00<00:00, 20704.64it/s]


In [ ]:
# 학습 데이터 셋 및 데이터 로더 생성 (위에서 생성한 w2v의 attribute들을 argument에 적절히 넣기)
dataset = CustomDataset(w2v.docs, w2v.word2id, w2v.window_size)
train_dataloader = DataLoader(dataset, 
                              batch_size = w2v.batch_size,
                              shuffle = True

)
len(train_dataloader)

35264

In [ ]:
# 학습
w2v.train(train_dataloader)

*****Epoch 0 Train Start*****
*****Epoch 0 Total Step 35264*****
Step: 500 Loss: 484.2486 lr: 0.0197
Step: 1000 Loss: 386.4143 lr: 0.0194
Step: 1500 Loss: 312.6190 lr: 0.0191
Step: 2000 Loss: 280.2149 lr: 0.0189
Step: 2500 Loss: 256.5084 lr: 0.0186
Step: 3000 Loss: 238.4600 lr: 0.0183
Step: 3500 Loss: 225.3050 lr: 0.0180
Step: 4000 Loss: 214.8932 lr: 0.0177
Step: 4500 Loss: 207.3881 lr: 0.0174
Step: 5000 Loss: 200.4794 lr: 0.0172
Step: 5500 Loss: 196.9314 lr: 0.0169
Step: 6000 Loss: 191.5448 lr: 0.0166
Step: 6500 Loss: 189.0682 lr: 0.0163
Step: 7000 Loss: 184.9562 lr: 0.0160
Step: 7500 Loss: 182.5988 lr: 0.0157
Step: 8000 Loss: 179.2890 lr: 0.0155
Step: 8500 Loss: 178.5331 lr: 0.0152
Step: 9000 Loss: 176.7237 lr: 0.0149
Step: 9500 Loss: 175.3078 lr: 0.0146
Step: 10000 Loss: 174.2316 lr: 0.0143
Step: 10500 Loss: 173.1132 lr: 0.0140
Step: 11000 Loss: 172.1300 lr: 0.0138
Step: 11500 Loss: 170.5542 lr: 0.0135
Step: 12000 Loss: 170.5382 lr: 0.0132
Step: 12500 Loss: 168.9157 lr: 0.0129
Step:

### 유사한 단어 확인
- 사전에 존재하는 단어들과 유사한 단어를 검색해보자. Gensim 패키지는 유사 단어 외에도 단어간의 유사도를 계산하는 여러 함수를 제공한다. 실험을 통해 word2vec의 한계점을 발견했다면 아래에 markdown으로 작성해보자. 
- [Gensim 패키지 document](https://radimrehurek.com/gensim/models/keyedvectors.html)

In [ ]:
import gensim

In [ ]:
word_vectors = gensim.models.KeyedVectors.load_word2vec_format('/content/drive/MyDrive/word2vec_wiki/w2v_1.txt', binary=False)

In [ ]:
word_vectors.most_similar(positive=None)

ValueError: ignored

word2vec의 한계점은?